### ISSUE TITLE
Code reuse

### ISSUE THREAD

**Issue by FredsoNerd** [own-pt/delphin-rdf#13]
I noticed the `delphin.cli.profile_to_*_rdf` modules have almost the same code. We should, eventually, invest um code reuse. An auxiliary function/subcomand such like `delphin.cli.profile_to_rdf` receiving an additional parameter may be enough to solving this issue.

**Comment by yfaria** [comment]
I agree, but if we think of those serializers as a future codec it would make some sense to keep them separated (maybe not, because we could make a call of the function with a general `profile-to-rdf` with the parameter in the code)

**Comment by FredsoNerd** [comment]
Yes. Consider codecs aren't the priority; if fact, they aren't even certain. I've just developed a general purpose solution, a `profile-to-rdf` subcomand, wich attempts to be modularized, best option for future possible semantic representations.

**Comment by yfaria** [comment]
See #18.
After #20, the only subcommand remaining is `delphin.cli.profile_to_rdf`. The conformity with PyDelphin codecs may be handled in the future.
