### ISSUE TITLE
README

### ISSUE THREAD

**Issue by arademaker** [own-pt/delphin-rdf#22]
We need a step-by-step example of how to use the code in a python program. We have so far focused on the use of the CLI interface, but a python programmer may need to use the lib to convert one specific sentence to RDF.

Please add it in the README

**Comment by yfaria** [comment]
Put the profile serialization example in 696bbc84a989e4919a305256a86026c52f090300
The case of only one sentence can be seen as a subcase because the main functions receives MRS/DMRS/EDS objects.
