### ISSUE TITLE
uri

### ISSUE THREAD

**Issue by arademaker** [own-pt/delphin-rdf#4]
we need to define a schema for uris 

http://example.com/ins/xpto/...

http://example.com/ins/mrs/1

http://example.com/ins/mrs/1/h0
http://example.com/ins/mrs/1#h0
http://example.com/ins/mrs/1-h0

http://example.com/ins/mrs/1/var/h0
http://example.com/ins/mrs/1/h/0
http://example.com/ins/mrs/1/x/0

http://example.com/ins/mrs/1/ep/0
http://example.com/ins/mrs/1/hcons/0

**Comment by FredsoNerd** [comment]
Just avoiding to leave those URI schemas as comments inside our code, so:

http://example.com/{item}/{mrsid}/HCONS/{relid}
http://example.com/{item}/{mrsid}/ICONS/{relid}
http://example.com/{item}/{mrsid}/RELS/{relid}
http://example.com/{item}/{mrsid}/VARIABLES/{varid}

**Comment by FredsoNerd** [comment]
We're using a URI schema `[prefix]/[identifier]/[HCONS|ICONS|RELS| ... ]#[NODE]`, for instance. May not we close this discussion?

**Comment by arademaker** [comment]
I believe we may still need some thoughts. I the profile, http://moin.delph-in.net/ItsdbProfile, we have items, parses, and results. An item may have more than 1 parse and it parse more than one result (need to double-check that, I will do later today!). 

Anyway, the uris may need to have the item-id and result-id on it.

prefix = namespace

prefix / item-id / result-id /{hcons|icons|rels|nodes}/ID

**Comment by arademaker** [comment]
this is the same of #19

**Comment by arademaker** [comment]
We may need to revise the URI patterns for each semantic representation. We are discussing DRMS in #21 . Later we can open specific issues for MRS, EDS, RMRS, etc. We fixed that the RDFs are produced from profiles. So we should adopt the same terminology from DELPH-IN and TSDB.
